name: auto-publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    environment:
      name: auto-publish
    concurrency:
      group: ${{github.workflow}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run
        run: |
          docker build -f autopublish.Dockerfile -t autopublish:latest .
          docker run --rm -e "STEAM_USERNAME=${{secrets.STEAM_USERNAME}}" -e "STEAM_PASSWORD=${{secrets.STEAM_PASSWORD}}" -e "GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}" autopublish:latest
