name: publish

on:
  workflow_dispatch:
    inputs:
      manifest_id:
        description: "Manifest ID to build"
        required: true

run-name: ${{inputs.manifest_id}}

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      image_base: benfiola/seven-days-to-die
    environment:
      name: publish
    concurrency:
      group: ${{github.workflow}}-${{inputs.manifest_id}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: calculate facts
        id: facts
        run: |
          manifest_id="${{inputs.manifest_id}}"
          docker_image="docker.io/${{env.image_base}}:${manifest_id}"

          echo "manifest_id=${manifest_id}" >> "${GITHUB_OUTPUT}"
          echo "docker_image=${docker_image}" >> "${GITHUB_OUTPUT}"
      - name: docker login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: benfiola
          password: ${{secrets.DOCKER_TOKEN}}
      - name: docker build + push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./entrypoint.Dockerfile
          push: true
          tags: |
            ${{steps.facts.outputs.docker_image}}
          build-args: |
            MANIFEST_ID=${{steps.facts.outputs.manifest_id}}
